services:
  db:
    image: postgres:17
    container_name: postgres_secret_santa
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: secret_santa
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secret-santa

volumes:
  postgres_data:

networks:
  secret-santa:
    driver: bridge

