
services:
  db:
    image: postgres:17
    container_name: postgres_secret_santa
    restart: always
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=password123
    - POSTGRES_DB=secret_santa
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "secret_santa"]
      timeout: 15s
      retries: 10
      start_period: 30s
      interval: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flyway

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://db:5432/secret_santa -user=admin -password=password123 -connectRetries=60 migrate
    volumes:
      - ./db.migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flyway

networks:
  flyway:
    driver: bridge

volumes:
  postgres_data:

